language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g gulp-cli
  - npm install -g ionic@latest cordova@latest
  - bower install
script:
  - gulp
  - ionic cordova platform add android
  - ionic cordova build android
os: osx
env:
 global:
 - ANDROID_API=26
 - EMULATOR_API=26
 - ANDROID_BUILD_TOOLS=26.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes
