language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - bower install
  - npm install -g gulp-cli
  - npm install -g ionic@latest cordova@latest
script: gulp travis
