language:
  - node_js
  - android
sudo: required
jdk: oraclejdk8
node_js:
  - "stable"
android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-$EMULATOR_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
 - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+
cache:
  directories:
    - "node_modules"
install:
  - npm install -g gulp-cli
  - npm install -g ionic@latest cordova@latest
  - bower install
script:
  - gulp
  - ionic cordova platform add android
  - ionic cordova build android
os: osx
env:
 global:
 - ANDROID_API=26
 - EMULATOR_API=26
 - ANDROID_BUILD_TOOLS=26.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes
